import { assessDataQuality, QualityResult } from './dataQuality';
import { CommuteRecord, WorkSchedule } from './types';
import { DEFAULT_WORK_SCHEDULE, getWorkdaySchedule, workTimeToMinutes } from './store';

export type StatsPeriod = 'week' | 'month' | 'year';
export interface TrendPoint { date: string; label: string; arrivalMinutes: number | null; durationMinutes: number | null; }
export interface BreakdownItem { label: string; count: number; averageMinutes?: number; }
export interface PeriodRange { start: Date; end: Date; label: string; }
export interface WeeklyReport { sampleSize: number; averageMinutes: number | null; variabilityMinutes: number | null; stableWeekday: string | null; lateCauseCandidates: string[]; actions: string[]; }
export interface MonthlyStats { monthRecords: CommuteRecord[]; commuteArrivals: CommuteRecord[]; returnArrivals: CommuteRecord[]; earlyLeaves: CommuteRecord[]; vacations: CommuteRecord[]; sickDays: CommuteRecord[]; absences: CommuteRecord[]; activeDays: number; roundTripDays: number; timedTrips: number; avgCommuteDuration: number | null; avgReturnDuration: number | null; fastestTripDuration: number | null; challengingWeatherTrips: number; workStartMinutes: number; evaluatedCommutes: number; lateCount: number; lateRate: number | null; avgLateMinutes: number | null; quality: QualityResult; weekly: WeeklyReport; }
export interface PeriodStats extends MonthlyStats { range: PeriodRange; previousRange: PeriodRange; trend: TrendPoint[]; weatherBreakdown: BreakdownItem[] | null; transportBreakdown: BreakdownItem[] | null; }

const average = (values: number[]) => values.length ? Math.round(values.reduce((a,b)=>a+b,0)/values.length) : null;
function minutesOfDay(value?: string) { if (!value) return null; const d=new Date(value); return Number.isNaN(d.getTime())?null:d.getHours()*60+d.getMinutes(); }
export function formatMinutesOfDay(minutes:number){const n=Math.max(0,Math.min(1439,minutes));return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
const dateAt=(value:string)=>new Date(`${value}T12:00:00`);
const dayStart=(date:Date)=>{const d=new Date(date);d.setHours(0,0,0,0);return d;};
const dayEnd=(date:Date)=>{const d=new Date(date);d.setHours(23,59,59,999);return d;};
export function getPeriodRange(period:StatsPeriod,anchor:Date,offset=0):PeriodRange{const d=new Date(anchor);if(period==='week'){d.setDate(d.getDate()+offset*7);const start=dayStart(d);start.setDate(start.getDate()-((start.getDay()+6)%7));const end=dayEnd(start);end.setDate(end.getDate()+6);return{start,end,label:`${start.getMonth()+1}.${start.getDate()}–${end.getMonth()+1}.${end.getDate()}`};}if(period==='month'){const start=new Date(d.getFullYear(),d.getMonth()+offset,1);const end=dayEnd(new Date(start.getFullYear(),start.getMonth()+1,0));return{start,end,label:`${start.getFullYear()}년 ${start.getMonth()+1}월`};}const start=new Date(d.getFullYear()+offset,0,1);const end=dayEnd(new Date(start.getFullYear(),11,31));return{start,end,label:`${start.getFullYear()}년`};}
function rawField(record:CommuteRecord,names:string[]){const raw=record as unknown as Record<string,unknown>;for(const name of names)if(typeof raw[name]==='string'&&raw[name])return String(raw[name]);return null;}
function breakdown(records:CommuteRecord[],fields:string[],empty:string[]=[]){const rows=records.map(r=>({label:rawField(r,fields),duration:r.duration_minutes})).filter(x=>x.label&&!empty.includes(x.label));if(!rows.length)return null;const groups=new Map<string,{count:number;durations:number[]}>();rows.forEach(({label,duration})=>{const item=groups.get(label!)??{count:0,durations:[]};item.count++;if(typeof duration==='number')item.durations.push(duration);groups.set(label!,item);});return[...groups].map(([label,item])=>({label,count:item.count,averageMinutes:average(item.durations)??undefined})).sort((a,b)=>b.count-a.count);}
function weeklyReport(records:CommuteRecord[]):WeeklyReport{const durations=records.filter(r=>r.type==='commute').map(r=>r.duration_minutes!).filter(Number.isFinite);const mean=durations.length?durations.reduce((a,b)=>a+b,0)/durations.length:null;const variability=mean===null?null:Math.round(Math.sqrt(durations.reduce((s,v)=>s+(v-mean)**2,0)/durations.length));return{sampleSize:durations.length,averageMinutes:average(durations),variabilityMinutes:variability,stableWeekday:null,lateCauseCandidates:[],actions:[durations.length?'이동시간 추이를 확인해 여유 출발 시간을 조정해 보세요.':'기록이 쌓이면 맞춤 제안을 드릴게요.']};}
export function computePeriodStats(records:CommuteRecord[],period:StatsPeriod,anchor:Date,schedule:WorkSchedule=DEFAULT_WORK_SCHEDULE,excludedIds:Set<string>=new Set()):PeriodStats{const range=getPeriodRange(period,anchor),previousRange=getPeriodRange(period,anchor,-1);const input=records.filter(r=>{const d=dateAt(r.date);return d>=range.start&&d<=range.end&&!excludedIds.has(r.id);});const quality=assessDataQuality(input),monthRecords=quality.validRecords,commuteArrivals=monthRecords.filter(r=>r.type==='commute'),returnArrivals=monthRecords.filter(r=>r.type==='return');const commuteDurations=commuteArrivals.map(r=>r.duration_minutes!).filter(Number.isFinite),returnDurations=returnArrivals.map(r=>r.duration_minutes!).filter(Number.isFinite);const evaluations=commuteArrivals.map(record=>{const arrival=minutesOfDay(record.end_time),day=getWorkdaySchedule(schedule,dateAt(record.date));return arrival===null||day.mode!=='office'?null:arrival-workTimeToMinutes(day.startTime);}).filter((v):v is number=>v!==null),lateMinutes=evaluations.filter(v=>v>0),commuteDates=new Set(commuteArrivals.map(r=>r.date)),returnDates=new Set(returnArrivals.map(r=>r.date));const trend=commuteArrivals.map(record=>({date:record.date,label:new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric'}).format(dateAt(record.date)),arrivalMinutes:minutesOfDay(record.end_time),durationMinutes:record.duration_minutes??null})).sort((a,b)=>a.date.localeCompare(b.date));return{range,previousRange,monthRecords,commuteArrivals,returnArrivals,earlyLeaves:monthRecords.filter(r=>r.type==='early_leave'),vacations:monthRecords.filter(r=>r.type==='vacation'),sickDays:monthRecords.filter(r=>r.type==='sick'),absences:monthRecords.filter(r=>r.type==='absence'),activeDays:new Set(monthRecords.map(r=>r.date)).size,roundTripDays:[...commuteDates].filter(d=>returnDates.has(d)).length,timedTrips:commuteDurations.length+returnDurations.length,avgCommuteDuration:average(commuteDurations),avgReturnDuration:average(returnDurations),fastestTripDuration:[...commuteDurations,...returnDurations].length?Math.min(...commuteDurations,...returnDurations):null,challengingWeatherTrips:[...commuteArrivals,...returnArrivals].filter(r=>['caution','alert','danger'].includes(r.weather_condition??'')).length,workStartMinutes:workTimeToMinutes(schedule.startTime),evaluatedCommutes:evaluations.length,lateCount:lateMinutes.length,lateRate:evaluations.length?Math.round(lateMinutes.length/evaluations.length*100):null,avgLateMinutes:average(lateMinutes),quality,weekly:weeklyReport(monthRecords),trend,weatherBreakdown:breakdown([...commuteArrivals,...returnArrivals],['weather_condition'],['normal','clear']),transportBreakdown:breakdown([...commuteArrivals,...returnArrivals],['transport_mode','transportation','mode'])};}
export function computeMonthlyStats(records:CommuteRecord[],now:Date,workStartMinutes=540):MonthlyStats{return computePeriodStats(records,'month',now,{...DEFAULT_WORK_SCHEDULE,startTime:formatMinutesOfDay(workStartMinutes)});}
export function comparisonPercent(current:number|null,previous:number|null){if(current===null||previous===null||previous===0)return null;return Math.round((current-previous)/previous*100);}
export function getStatsFallbackComment(stats:MonthlyStats){if(!stats.monthRecords.length)return'아직 분석할 기록이 없어요. 출퇴근을 완료하면 리포트를 만들게요.';if(!stats.evaluatedCommutes)return'근무일의 도착 시각이 있는 출근 기록이 필요해요.';if(!stats.lateCount)return`평가 가능한 출근 ${stats.evaluatedCommutes}건이 모두 정시였어요.`;return`평가 가능한 출근 ${stats.evaluatedCommutes}건 중 ${stats.lateCount}건이 늦었어요. 평균 ${stats.avgLateMinutes}분의 여유를 더해 보세요.`;}
